name: MSBuild

on:
  push:
    branches: [ "test_build" ]
  pull_request:
    branches: [ "master" ]

env:
  LINGUINI_FILE_PATH: linguini\linguini.sln
  REMY_FILE_PATH: remy\remy.sln

  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build_linguini:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages for linguini
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.LINGUINI_FILE_PATH}}

    - name: Build linguini solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.LINGUINI_FILE_PATH}} /p:Configuration=${{ env.BUILD_CONFIGURATION }} -v:Normal -fl -flp:logfile=linguini_msbuild.log;verbosity=Normal

    - name: Upload linguini build log
      uses: actions/upload-artifact@v4
      with:
        name: linguini_build_log
        path: linguini_msbuild.log

    - name: Upload linguini artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linguini
        path: linguini/bin/${{env.BUILD_CONFIGURATION}}

  build_remy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages for remy
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.REMY_FILE_PATH}}

    - name: Build remy solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.REMY_FILE_PATH}} /p:Configuration=${{ env.BUILD_CONFIGURATION }} -v:Normal -fl -flp:logfile=remy_msbuild.log;verbosity=Normal

    - name: Upload remy build log
      uses: actions/upload-artifact@v4
      with:
        name: remy_build_log
        path: remy_msbuild.log

    - name: Upload remy artifacts
      uses: actions/upload-artifact@v4
      with:
        name: remy
        path: remy/bin/${{env.BUILD_CONFIGURATION}}
