# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "test_build" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  LINGUINI_FILE_PATH: linguini\linguini.sln
  REMY_FILE_PATH: remy\remy.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build_linguini:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages for linguini
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.LINGUINI_FILE_PATH}}

    - name: Build linguini solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.LINGUINI_FILE_PATH}} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /fl /flp:logfile=linguini_msbuild.log;verbosity=diagnostic

    - name: Upload linguini artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linguini
        path: linguini/bin/${{env.BUILD_CONFIGURATION}}
  build_remy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages for remy
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.REMY_FILE_PATH}}

    - name: Build remy solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.REMY_FILE_PATH}} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /fl /flp:logfile=remy_msbuild.log;verbosity=diagnostic

    - name: Upload remy artifacts
      uses: actions/upload-artifact@v4
      with:
        name: remy
        path: remy/bin/${{env.BUILD_CONFIGURATION}}

